set-option -g default-shell /bin/zsh
set-option -g default-terminal "screen-256color"
set-option -g default-command /bin/zsh

set-option -sg escape-time 10
set-option -g status-interval 5
set-option -g visual-activity on
set-window-option -g monitor-activity on
set -g renumber-windows on

set -g prefix C-b
bind C-b send-prefix

set -g base-index 1

unbind %
unbind Left
unbind Down
unbind Up
unbind Right

bind s split-window -h -c "#{pane_current_path}"
bind i split-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r ^h resize-pane -L
bind -r ^j resize-pane -D
bind -r ^k resize-pane -U
bind -r ^l resize-pane -R

set -g status-style "bg=cyan,fg=black"
set -g window-status-current-style "bg=black,fg=cyan"
set -g window-status-style "bg=cyan,fg=black"
set -g window-status-separator " | "


set -g pane-border-style "fg=white"
set -g pane-active-border-style "fg=cyan"
