set-option -g default-shell /bin/zsh
set-option -g default-command /bin/zsh


set -g status-style "bg=cyan,fg=black"
set -g window-status-current-style "bg=black,fg=cyan"
set -g window-status-style "bg=cyan,fg=black"
set -g window-status-separator " | "

